# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eprotobuf.proto\"\x1b\n\x0bRequestBody\x12\x0c\n\x04name\x18\x01 \x01(\t\"-\n\rQueryResponse\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\"\x1d\n\x0b\x42uyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"1\n\x03Toy\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x32^\n\x0eToyStoreServer\x12\'\n\x05Query\x12\x0c.RequestBody\x1a\x0e.QueryResponse\"\x00\x12#\n\x03\x42uy\x12\x0c.RequestBody\x1a\x0c.BuyResponse\"\x00\x62\x06proto3'
)




_REQUESTBODY = _descriptor.Descriptor(
  name='RequestBody',
  full_name='RequestBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RequestBody.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=45,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock', full_name='QueryResponse.stock', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='QueryResponse.price', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=92,
)


_BUYRESPONSE = _descriptor.Descriptor(
  name='BuyResponse',
  full_name='BuyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='BuyResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=123,
)


_TOY = _descriptor.Descriptor(
  name='Toy',
  full_name='Toy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Toy.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stock', full_name='Toy.stock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='Toy.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['RequestBody'] = _REQUESTBODY
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['BuyResponse'] = _BUYRESPONSE
DESCRIPTOR.message_types_by_name['Toy'] = _TOY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestBody = _reflection.GeneratedProtocolMessageType('RequestBody', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTBODY,
  '__module__' : 'protobuf_pb2'
  # @@protoc_insertion_point(class_scope:RequestBody)
  })
_sym_db.RegisterMessage(RequestBody)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'protobuf_pb2'
  # @@protoc_insertion_point(class_scope:QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)

BuyResponse = _reflection.GeneratedProtocolMessageType('BuyResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUYRESPONSE,
  '__module__' : 'protobuf_pb2'
  # @@protoc_insertion_point(class_scope:BuyResponse)
  })
_sym_db.RegisterMessage(BuyResponse)

Toy = _reflection.GeneratedProtocolMessageType('Toy', (_message.Message,), {
  'DESCRIPTOR' : _TOY,
  '__module__' : 'protobuf_pb2'
  # @@protoc_insertion_point(class_scope:Toy)
  })
_sym_db.RegisterMessage(Toy)



_TOYSTORESERVER = _descriptor.ServiceDescriptor(
  name='ToyStoreServer',
  full_name='ToyStoreServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=176,
  serialized_end=270,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='ToyStoreServer.Query',
    index=0,
    containing_service=None,
    input_type=_REQUESTBODY,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Buy',
    full_name='ToyStoreServer.Buy',
    index=1,
    containing_service=None,
    input_type=_REQUESTBODY,
    output_type=_BUYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOYSTORESERVER)

DESCRIPTOR.services_by_name['ToyStoreServer'] = _TOYSTORESERVER

# @@protoc_insertion_point(module_scope)
